version: "3.8"
services:
  app:
    build:
      context: ./
      target: app_node
    volumes:
      - ./:/srv/app
      - /srv/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - mongo_db:/data/db

volumes:
    mongo_db:
      external: true
